### ISSUE TITLE
Wrong casting causes invalid addresses

### ISSUE THREAD

**Issue by dennistreysa** [gngz/24LC256-Arduino-Library#2]
When writing the upper part of the byte-address, the following code is used:

```c++
Wire.write((byte) address>>8);
```

Which causes a problem with addresses above 0x00ff since it will cast the address to a byte first and then shift it to the right, which causes the upper byte to be always 0.

You can check this via:

```c++
mem1.writeByte(0x0000, 42);

Serial.println(mem1.readByte(0x0000));
Serial.println(mem1.readByte(0x0100));
Serial.println(mem1.readByte(0x1200));
```

They will all print out '42'.

**Comment by dennistreysa** [comment]
I created a pull request which should do the trick, maybe you can have a look at it: #3

**Comment by gngz** [comment]
Thank you for your contribution.
